export const domain_options = [
    "Career Development",
    "Personal Growth",
    "Technology and Programming",
    "Business and Entrepreneurship",
    "Finance and Investment",
    "Academic Tutoring",
    "Creative Arts (Design, Music, Writing, etc.)",
    "Health and Wellness",
    "Fitness and Sports Coaching",
    "Mental Health and Emotional Support",
    "Leadership and Management",
    "Marketing and Branding",
    "Public Speaking and Communication",
    "Language Learning",
    "STEM Education",
    "Networking and Relationship Building",
    "Time Management and Productivity",
    "Startups and Innovation",
    "Legal and Compliance Guidance",
    "Parenting and Family Support"
  ]